### ISSUE TITLE
NFT <> NFT Trades are not supported by V4 SDK

### ISSUE THREAD

**Issue by wizardlabsxyz** [trader-xyz/nft-swap-sdk#102]
Hello! I'm trying to test out the NFT <> NFT trades with V4 and it looks like that isn't supported yet. I understand from the error messages I receive that I should use V3 instead for this. 

Now that I'm trying to use V3 SDK I find that the addresses.json of V3 SDK does not include chainId 5. 

I would like to use a testnet with NFT <> NFT trades and since rinkeby is deprecated it would be awesome if you could update the addresses.json to include testnet Goerli (chain 5).

Another question regarding Goerli and V3. Will the V3 version of the SDK work with the protocol contracts deployed to Goerli?

**Comment by jinsley8** [comment]
The 0x contracts aren't deployed to newer Ethereum testnets.

You're better off getting it working with Polygon since it's lower cost then make adjustments for Eth mainnet and run a few tests with that. Although gas is expensive.

**Comment by johnrjj** [comment]
Yeah, the 0x core team has not deployed v3 to any current (goerli, sepolia) testnets. 

unfortunately the v3 contracts are quire cumbersome to deploy, although I can definitely try -- I have the repo locally

**Comment by wizardlabsxyz** [comment]
Thanks for the replies, I decided to work with polygon mumbai testnet for now since V3 is deployed there. While I have you guys here though... Do we have any idea on when V4 will support NFT <> NFT trades?

**Comment by johnrjj** [comment]
Not sure: re NFT<>NFT swaps. That's something I've been requesting. I'm unfortunately not involved with the core team and don't have much visibility into the protocol roadmap at the moment. I've been trying to get 0x Labs to put it on the roadmap for a bit now. I think it's worth proposing something on the governance forum now that governance has been revamped -- I've been meaning to do it.

**Comment by wizardlabsxyz** [comment]
If I can support this effort in anyway please do let me know. I have a client that is invested in this software and we will need V4 to support NFT <> NFT trades very soon.
