### ISSUE TITLE
Intermittent Failures with loadApprovalStatus

### ISSUE THREAD

**Issue by wizardlabsxyz** [trader-xyz/nft-swap-sdk#104]
Getting errors on polygon PoS (137) when trying to check approval status. Sometimes I try to load status for a single token, sometimes I try to load for a number of tokens i.e. 3-6 tokens. The issue is intermittent but it fails more often that it succeeds. My gut tells me i'm getting rate limited somehow. Swap SDK is configured to use the provider injected onto the window by metamask.

```
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getApproved(uint256)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
```

**Comment by wizardlabsxyz** [comment]
Example of a token im trying to load approval status for
https://opensea.io/assets/matic/0x19b45806c2452b6321d456108f8a48b469a21dfe/2211

**Comment by wizardlabsxyz** [comment]
Sometimes the method in the error is getApproved, sometimes it's isApprovedForAll. Not sure why it would be one or the other and not the same one every time.

**Comment by wizardlabsxyz** [comment]
I changed the provider from a metamask provider to an alchemy provider and that cleared this up. No idea why metamask was rate limiting because I wasn't making that many calls but who knows.

**Comment by jinsley8** [comment]
> I changed the provider from a metamask provider to an alchemy provider and that cleared this up. No idea why metamask was rate limiting because I wasn't making that many calls but who knows.

I've also had issues before when I use `wagmi` with anything but the Alchemy provider. Not sure why that happens.
