### ISSUE TITLE
Signature on signed order is invalid

### ISSUE THREAD

**Issue by koin-marian** [trader-xyz/nft-swap-sdk#74]
I am getting a "Signature on signed order is invalid" when trying to post to the public orderbook. The orders are signed through MetaMask.

**Comment by johnrjj** [comment]
@koin-marian Which chain are you using?

**Comment by koin-marian** [comment]
> 

Rinkeby (4)

**Comment by johnrjj** [comment]
Rinkeby is not support with v4. Only ropsten (previously)

Closing this issue as we're now on Goerli for testnet
