### ISSUE TITLE
Impossible to create ETH → NFT order with "buildOrder" method

### ISSUE THREAD

**Issue by ErnestMironov** [trader-xyz/nft-swap-sdk#77]
It is possible to create an NFT → ETH order, but it is impossible to create ETH → NFT.

A transaction ERC-20 → NFT fails with an error "cannot estimate gas", although a transaction ERC-20 (native token) → NFT passes successfully.

**Comment by johnrjj** [comment]
No, you cannot programmatically move ETH via contract like that unfortunately -- you can only use ETH as the taker.
