### ISSUE TITLE
Support of Rinkeby testnet in V4

### ISSUE THREAD

**Issue by ErnestMironov** [trader-xyz/nft-swap-sdk#82]
in V4 Ropsten is supported, but not Rinkeby. It would be great features, since for testing it could be necessary to use OpenSea (supports Rinkeby, but not Ropsten)

**Comment by koin-marian** [comment]
Agreed.

**Comment by johnrjj** [comment]
Goerli is the main testnet as of https://github.com/trader-xyz/nft-swap-sdk/releases/tag/v0.29.0
