### ISSUE TITLE
call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getApproved(uint256)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)

### ISSUE THREAD

**Issue by zqdevelopment** [trader-xyz/nft-swap-sdk#90]
I'm trying to create a transaction "ERC20 Example", but I'm encountering this problem: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getApproved(uint256)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
![image](https://user-images.githubusercontent.com/54170448/188431282-5b2899ec-e75b-4c1c-bb2c-6af86e6eb15a.png)
This error is thrown by this function nftSwapSdk.loadApprovalStatus()

**Comment by johnrjj** [comment]
Hey there! Thanks for reporting an issue;

Which network and which contract address are you trying to load an approval for?

**Comment by johnrjj** [comment]
Fixed in Discord
