### ISSUE TITLE
V3 fillSignedOrder - MetaMask - RPC Error when signing

### ISSUE THREAD

**Issue by jinsley8** [trader-xyz/nft-swap-sdk#94]
Hi,

I'm working with V3 on Polygon and getting a Metamask internal error when using `fillSignedOrder`.

Before filling I verify the order signature is correct and that it passes.

Does anyone know what could be causing the following issue when using `fillSignedOrder` results in:
```
MetaMask - RPC Error: Internal JSON-RPC error.
code: -32603
data: 
    code: 3
    data: "0x4678472b43693c6356dfe50fa860e046b18bfc620c5c855517bfab74eebfdcb898531f4a00000000000000000000000000000000000000000000000000......."
    message:  "execution reverted"
message: "Internal JSON-RPC error."

```

**Comment by johnrjj** [comment]
If you manually provide a high gas limit to the transaction, and force the transaction to go through and fail, I can help debug if you can provide the reverted tx hash

**Comment by jinsley8** [comment]
@johnrjj thank you!

I've tried all different configs for `fillSignedOrder` and can't get past this Metamask error. Everything is good up until this point. Metamask 

I tried using the `useFeeData` hook from the `wagmi` package to get gasPrices too.

```
const fillTx = await swapSdk.fillSignedOrder(normalizedOrder, swapSdk.exchangeContract.address, {
                // gasPrice,
                // maxPriorityFee: gasPrice?.maxFeePerGas,
                // maxFee: gasPrice?.maxPriorityFeePerGas,
                gasLimit: '5000000000',
                // HACK(johnnrjj) - Rinkeby still has protocol fees, so we give it a little bit of ETH so its happy.
                // value: ethers.utils.parseEther('0.001'),
            });
```

**Comment by jinsley8** [comment]
Also, after I accept `setApprovalForAll()` for an NFT contract via `loadApprovalStatus`:

```
const approvalStatusForUserB = await swapSdk.loadApprovalStatus(
                data.result[0].takerAssets[0],
                data.result[0].taker
            );
```

It returns:
```
{ 
  contractApproved: true,
  tokenIdApproved: false

}
```

Does anyone know if `tokenIdApproved` ever has to be set to true here?

**Comment by jinsley8** [comment]
Could it have something to do with EIP1559 transaction fees?

https://wiki.polygon.technology/docs/develop/eip1559-transactions/how-to-send-eip1559-transactions/

`TransactionOverrides` interface does include this info though:
https://github.com/trader-xyz/nft-swap-sdk/blob/8b3c3ebfa868cbbb1beb59f49521b956faed0201/src/sdk/common/types.ts#L42-L51

**Comment by jinsley8** [comment]
Closing, this seems to be just a configuration error when building order.
